### ISSUE TITLE
Compatibility With Sitecore XA.Reference

### ISSUE THREAD

**Issue by Shaurabhbhatt** [alan-null/XA.Reference#4]
Hi,
I want to confirm can I use the following versions required for XA.Reference
1.- SXA 1.5
2.- XP 8.2 Upd-5
3.- Sitecore PowerShell Extensions 4.7

Can I use this solution with above versions of resources.

**Comment by alan-null** [comment]
Hi,

**yes**



| Product   |      Version      |  Revision |
|----------|:-------------:|:------:|
| Sitecore |  **8.2** | rev. 170728 |
| SXA  |  **1.5** | rev. 171010|

source: [SXA 1.5](https://github.com/alan-null/XA.Reference/releases/tag/4.0)

**Comment by Shaurabhbhatt** [comment]
Thank you so much Alan
